### ISSUE TITLE
Host the Keptn in K3D demo

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn-sandbox/contributing#10]
### Feature Request

@agardnerIt has recently created a new demo for Keptn that does not require K8s. It would be good to make it official to simplify adoption by users. So I suggest hosting it in Keptn repos. https://github.com/keptn/keptn.github.io/pull/1073 for the documentation update

### Checklist

- [ ] - Repository transfer: https://github.com/agardnerIT/thekindkeptn
- [ ] - GitHub access permissions

### Sponsors

- @oleg-nenashev 

### References

* Source GitHub repository: https://github.com/agardnerIT/thekindkeptn
* Documentation PR: https://github.com/keptn/keptn.github.io/pull/1073

**Comment by grabnerandi** [comment]
approved from my side

**Comment by thschue** [comment]
ok from my side

**Comment by johannes-b** [comment]
One concern from my side. 

Going with KinD would be a second option for the quickstart: (1) `KinD` and (2) `K3d`. This makes it even more difficult for the end-user because the user does not know which one to follow.

Shouldn't we focus on one approach; either KinD or K3d?

**Comment by agardnerIT** [comment]
@johannes-b actually my demo is no longer using KinD. I found it to be too flaky. My demo also uses `k3d` the only difference really between the two creation options is that mind bundles `k3d` and `helm` inside the container then uses the `k3d` in the container to create the cluster. The other option mandates that the user installs `k3d` themselves.

When the `docker run` command is executed, the first thing that happens is `k3d cluster create...`: https://github.com/agardnerIT/thekindkeptn/blob/c9abe99649bcc28705f2bd390d892d4adf8a7b75/install_script.sh#L36

**Comment by johannes-b** [comment]
@agardnerIT okay, thanks for the clarification!
