### ISSUE TITLE
Hosting request GSoC 2022: New Documentation Site Engine

### ISSUE THREAD

**Issue by iamrajiv** [keptn-sandbox/contributing#14]
### Feature Request

Separate repository for the `New Documentation Site Engine` project in [https://github.com/keptn-sandbox](https://github.com/keptn-sandbox). All the code and new documentation site engine will be pushed to this repository.

### References

All the updates and references I will add to the following repositories:

- [https://github.com/keptn/community/tree/main/mentorship/gsoc/2022/projects/new-docs-site-engine](https://github.com/keptn/community/tree/main/mentorship/gsoc/2022/projects/new-docs-site-engine)
- [https://github.com/iamrajiv/GSoC-2022](https://github.com/iamrajiv/GSoC-2022)

**Comment by oleg-nenashev** [comment]
I support

**Comment by thschue** [comment]
I support

**Comment by oleg-nenashev** [comment]
Done: https://github.com/keptn-sandbox/new-keptn-docs-engine
