### ISSUE TITLE
 Hosting request GSoC 2022: K6 Integration Service

### ISSUE THREAD

**Issue by jainammm** [keptn-sandbox/contributing#15]
### Description
Separate repository for the K6 Integration Service project in https://github.com/keptn-sandbox. All the code will be pushed to this repository.

PS: Please keep the repository name as `k6-service` under `keptn-sandbox`.

### Checklist
- [x] Repository transfer: https://github.com/jainammm/keptn-k6-service
- [ ] GitHub access permissions
- [x] Repository author has followed the [hosting guide](https://github.com/keptn-sandbox/contributing/blob/master/CONTRIBUTING.md): 
  - [x] README.md
  - [x] Licence
  - [x] CODEOWNERS (with my git account)
  
### References

- Project Page: https://github.com/keptn/community/tree/main/mentorship/gsoc/2022/projects/k6-integration-service

**Comment by oleg-nenashev** [comment]
I support

**Comment by thschue** [comment]
I support

**Comment by oleg-nenashev** [comment]
Done! https://github.com/keptn-sandbox/k6-service
