### ISSUE TITLE
Hosting request: SLI provider integration for Sumo Logic

### ISSUE THREAD

**Issue by vadasambar** [keptn-sandbox/contributing#16]
### Description
I want to host my WIP SLI provider for Sumo Logic https://github.com/vadasambar/sumologic-service in keptn-sandbox so that it saves me some work around fixing the repo CI and image registry to make it work (CI and image registry assumes `keptn-sandbox` as the org)

### Checklist
- [ ] Repository transfer: [sumologic-service](https://github.com/vadasambar/sumologic-service)
- [ ] GitHub access permissions
- [ ] Repository author has followed the [hosting guide](https://github.com/keptn-sandbox/contributing/blob/master/CONTRIBUTING.md)

**Comment by oleg-nenashev** [comment]
I support

**Comment by thschue** [comment]
I support

**Comment by oleg-nenashev** [comment]
Done! https://github.com/keptn-sandbox/sumologic-service
