### ISSUE TITLE
Hosting Request: Keptn Lifecycle Controller

### ISSUE THREAD

**Issue by thschue** [keptn-sandbox/contributing#18]
### Description

This repository will contain the prototype for the Keptn Lifecycle Controller, which should control the delivery of cloud-native applications using pre- & post-deployment checks, as well as application health checks

### Checklist
- [X] Repository transfer: directly created in the keptn sandbox (https://github.com/keptn-sandbox/lifecycle-controller)
- [X] GitHub access permissions: added a group lifecycle-controller-maintainers
- [X] Repository author has followed the [hosting guide](https://github.com/keptn-sandbox/contributing/blob/master/CONTRIBUTING.md) 

### Sponsors
@grabnerandi 
@bacherfl 
@thisthat

**Comment by thisthat** [comment]
I support 👍

**Comment by bacherfl** [comment]
I support

**Comment by grabnerandi** [comment]
I support

**Comment by oleg-nenashev** [comment]
I support
