### ISSUE TITLE
Hosting request : Splunk Integration Service

### ISSUE THREAD

**Issue by kuro-jojo** [keptn-sandbox/contributing#23]
### Description
@Mouhamadou305 and I, @kuro-jojo worked on a splunk-service on behalf of **[Amadeus IT Group](https://github.com/AmadeusITGroup).** We have created an SLI-provider for splunk enterprise and added a remediation feature to the service.

### Checklist
- [x] Repository author has followed the [hosting guide](https://github.com/keptn-sandbox/contributing/blob/master/CONTRIBUTING.md) 
- [x] Repository transfer: moved under https://github.com/keptn-sandbox/splunk-sli-provider
- [x] GitHub access permissions: https://github.com/keptn/community/pull/301

### References

-  Source Github repository : **https://github.com/AmadeusITGroup/keptn-splunk-sli-provider**

**Comment by thisthat** [comment]
@kuro-jojo and @Mouhamadou305 please confirm that you have maintainer permissions for https://github.com/keptn-sandbox/splunk-sli-provider so we can close this ticket :)
