### ISSUE TITLE
Zendesk Service

### ISSUE THREAD

**Issue by ghost** [keptn-sandbox/contributing#5]
The zendesk service is ready to be moved to keptn-sandbox:

```
https://github.com/Dynatrace-Adam-Gardner/keptn-zendesk-service
```

**Comment by jetzlstorfer** [comment]
Hi @Dynatrace-Adam-Gardner ! Thanks for this contribution.
If you can add me as an admin to your repo we can start the migration process.

What needs to be done for the migration:

- [x] Migrate repo to keptn-sandbox
- [ ] Code review
- [ ] Setup of github CI workflow
- [ ] Change of images to match "keptnsandbox"
- [ ] Creation of releases so all needed image versions are built

**Comment by ghost** [comment]
I've initiated the transfer of ownership to you Juergen.
Zendesk have also been kind enough to set me up with a unlimited dev tenant and I've invited you as an administrator to that tenant `https://d3v-agardnerdt.zendesk.com/`

**Comment by jetzlstorfer** [comment]
Thanks, the project has been migrated to https://github.com/keptn-sandbox/zendesk-service

**Comment by jetzlstorfer** [comment]
Closing this issue as it will be taken care of here https://github.com/keptn-sandbox/zendesk-service/issues/1
