### ISSUE TITLE
AWS SSP Addons for keptn and keptn Remote Execution Planes

### ISSUE THREAD

**Issue by heckelmann** [keptn-sandbox/contributing#7]
Hi,

we would like to move out AWS SSP Addons (deploy keptn and remote execution planes using AWS CDK) to keptn Sandbox

Repository:
https://github.com/thschue/keptn-ssp-addons

CODEOWNERS File present

Owners @thschue and @heckelmann

Thank you and have a great day!

**Comment by oleg-nenashev** [comment]
@heckelmann @thschue transferring a repo from a personal account is not that trivial. It needs admin permissions which are available only to the owner for personal repos or a special transfer org. I can create one, similar to https://github.com/jenkinsci-transfer

**Comment by oleg-nenashev** [comment]
Created https://github.com/orgs/keptn-transfer and invited you both there

**Comment by oleg-nenashev** [comment]
Transfer is completed! https://github.com/keptn-sandbox/keptn-ssp-addons
