### ISSUE TITLE
Hosting request: Datadog Integration Service

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn-sandbox/contributing#9]
### Feature Request

Datadog is one of the popular monitoring systems. It would be awesome to have an official SLI Provider integration service for it. @vadasambar is working on this integration service, and I think we could host the current integration service in the Sandbox

### Checklist

- [x] - Repository transfer: https://github.com/keptn-sandbox/datadog-service
- [x] - GitHub access permissions
- [x] - NPM access permissions (N/A)

### Sponsors

- @oleg-nenashev 
- @grabnerandi 

### References

* Source GitHub repository: https://github.com/vadasambar/datadog-service

**Comment by oleg-nenashev** [comment]
I support FTR

**Comment by grabnerandi** [comment]
I also support this

**Comment by oleg-nenashev** [comment]
Done, welcome aboard @vadasambar!
![image](https://user-images.githubusercontent.com/3000480/154007729-a48da0ee-e41e-4404-a769-53089362e9de.png)
